spring:
  datasource:
    url: jdbc:mysql://localhost:33060/easy_mbp_enhance?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "password"
    # druid 连接池管理
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        config:
          enabled: true
        stat:
          enabled: true
      filters: stat,wall,slf4j
      initial-size: 5
      max-active: 20
      max-pool-prepared-statement-per-connection-size: -1
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 5
      pool-prepared-statements: false
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
      validation-query-timeout: 1
      stat-view-servlet:
        allow: 127.0.0.1
        enabled: true
        login-password: 123456
        login-username: root
        reset-enable: true
      web-stat-filter:
        enabled: true
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
        session-stat-enable: true
        session-stat-max-count: 100
        url-pattern: /*
  main:
    allow-circular-references: true

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

storage:
  type: local
  local:
    path: D:\upload，这里是本地图片存储地址
    public: http://我是外部访问链接，你使用可以本地搭建nginx服务器/
#    如果需要使用minio存储，请配置以下信息
#  minio:
#    endpoint: http://123123
#    public-url: http://123123
#    accessKey: minio
#    secretKey: minio123
#    bucketName: 123123

services:
  log:
    debug: false

mbp-enhance:
  debug: true
    #  generator:
    #    enable: true
    #    table:
    #  在启动时自动创建表，仅在开发环境使用，最好只在第一次启动时使用
    #      on-boot: true
    #  在启动时自动删除已有表，请谨慎使用
  #      drop-table: true
